# Makefile for snogray
#
#  Copyright (C) 2005  Miles Bader <miles@gnu.org>
#
# This file is subject to the terms and conditions of the GNU General
# Public License.  See the file COPYING in the main directory of this
# archive for more details.
#
# Written by Miles Bader <miles@gnu.org>
#

TARGETS = snogray snogcvt

all: $(TARGETS)

OPT = -O5 -fomit-frame-pointer
DEBUG = -g -Wall
#PG = -pg
#MUDFLAP = -fmudflap

CFLAGS = $(OPT) $(DEBUG) $(MACHINE_CFLAGS) $(PG) $(MUDFLAP)
CXXFLAGS = $(CFLAGS) -frepo
LDFLAGS = $(PG) $(MUDFLAP)

################################################################
##
## Per-host configuration
##

HOST_CFLAGS_dhapc248.dev.necel.com = $(ARCH_CFLAGS_pentium4)
ARCH_CFLAGS_pentium3 = -march=pentium3 -mfpmath=sse -msse
ARCH_CFLAGS_pentium4 = -march=pentium4 -mfpmath=sse -msse2
ARCH_CFLAGS_i686 = $(ARCH_CFLAGS_pentium3)

HOST := $(shell hostname)
ARCH := $(shell uname -m)
HOST_CFLAGS_$(HOST) ?= $(ARCH_CFLAGS_$(ARCH))
MACHINE_CFLAGS = $(HOST_CFLAGS_$(HOST))

################################################################
##
## Library configuration (mainly for image backends currently)
##

LIBPNG_CFLAGS	= $(shell libpng-config --cflags)
LIBPNG_LIBS	= $(shell libpng-config --libs)

LIBEXR_CFLAGS	= $(shell pkg-config OpenEXR --cflags)
LIBEXR_LIBS	= $(shell pkg-config OpenEXR --libs)

LIBJPEG_CFLAGS	=
LIBJPEG_LIBS	= -ljpeg

LIBNETPBM_CFLAGS =
LIBNETPBM_LIBS	= -lnetpbm

IMAGE_LIBS =	$(LIBPNG_LIBS) $(LIBEXR_LIBS) $(LIBJPEG_LIBS) $(LIBNETPBM_LIBS)

LIBS =		$(IMAGE_LIBS) $(MUDFLAP:-f%=-l%)

################################################################
##
## Grotty internal details of generating compiler options
##

# Tell gcc to generate dependency files
#
DEP_CFLAGS = -MMD -MF $(<:%.cc=.%.d)

# If compiling with -pg option, we can't use -fomit-frame-pointer, so
# filter it out.
#
_CFLAGS_FILT = $(if $(filter -pg,$(CFLAGS)),$(filter-out -fomit-frame-pointer,$(CFLAGS)),$(CFLAGS))
_CXXFLAGS_FILT = $(if $(filter -pg,$(CXXFLAGS)),$(filter-out -fomit-frame-pointer,$(CXXFLAGS)),$(CXXFLAGS))

# _CFLAGS and _CXXFLAGS are what the actual build rules use
#
_CFLAGS = $(_CFLAGS_FILT) $(DEP_CFLAGS)
_CXXFLAGS = $(_CXXFLAGS_FILT) $(DEP_CFLAGS)

################################################################
##
## Common sources between snogray and snogcvt
##

IMAGE_SRCS = image.cc image-aa.cc image-cmdline.cc image-dispatch.cc	\
	  image-exr.cc image-jpeg.cc image-ppm.cc image-png.cc		\
	  image-rgb-byte.cc

COMMON_SRCS = cmdlineparser.cc color.cc $(IMAGE_SRCS)

################################################################
##
## Snogray
##

SNOGRAY_SRCS = camera.cc glow.cc intersect.cc lambert.cc light-model.cc	\
	  material.cc mesh.cc mirror.cc obj.cc phong.cc primary-obj.cc	\
	  ray.cc scene.cc scene-load.cc scene-load-aff.cc snogray.cc	\
	  space.cc sphere.cc test-scenes.cc timeval.cc trace-state.cc	\
	  transform.cc triangle.cc voxtree.cc $(COMMON_SRCS)

SNOGRAY_OBJS = $(SNOGRAY_SRCS:.cc=.o)

snogray: $(SNOGRAY_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(SNOGRAY_OBJS) $(LIBS)

################################################################
##
## Snogcvt (image conversion program)
##

SNOGCVT_SRCS = snogcvt.cc $(COMMON_SRCS)

SNOGCVT_OBJS = $(SNOGCVT_SRCS:.cc=.o)

snogcvt: $(SNOGCVT_OBJS)
	$(CXX) -o $@ $(LDFLAGS) $(SNOGCVT_OBJS) $(LIBS)

################################################################
##
## Union of all source/object files, used in cleaning
##

ALL_SRCS = $(sort $(SNOGRAY_SRCS) $(SNOGCVT_SRCS))
ALL_OBJS = $(sort $(SNOGRAY_OBJS) $(SNOGCVT_OBJS))

################################################################
##
## Special build rules for image backends (mainly to supplement the
## include path)
## 

image-exr.o: image-exr.cc
	$(CXX) -c $(LIBEXR_CFLAGS) $(_CXXFLAGS) $<
image-png.o: image-png.cc
	$(CXX) -c $(LIBPNG_CFLAGS) $(_CXXFLAGS) $<
image-jpeg.o: image-jpeg.cc
	$(CXX) -c $(LIBJPEG_CFLAGS) $(_CXXFLAGS) $<
image-ppm.o: image-ppm.cc
	$(CXX) -c $(LIBNETPBM_CFLAGS) $(_CXXFLAGS) $<

################################################################
##
## Automatic dependency generation using gcc-generated .d files
##

DEPS = $(ALL_SRCS:%.cc=.%.d)
-include $(DEPS)

################################################################
##
## Our basic build rules
##

%.o: %.cc
	$(CXX) -c $(_CXXFLAGS) $<
%.s: %.cc
	$(CXX) -S $(_CXXFLAGS) $<

%.o: %.c
	$(CC) -c $(_CFLAGS) $<
%.s: %.c
	$(CC) -S $(_CFLAGS) $<


# These are generated by g++ -frepo
#
RPO_FILES = $(ALL_OBJS:%.o=%.rpo) 

clean:
	$(RM) $(TARGETS) $(ALL_OBJS) $(RPO_FILES) $(DEPS)

# Handy for seeing what options are being generated...
#
cflags:
	@echo "CFLAGS = $(CFLAGS)"
	@echo "MACHINE_CFLAGS = $(MACHINE_CFLAGS)"
	@echo "HOST_CFLAGS_$(HOST) = $(HOST_CFLAGS_$(HOST))"
	@echo "ARCH_CFLAGS_$(ARCH) = $(ARCH_CFLAGS_$(ARCH))"
	@echo "ARCH = $(ARCH)"
	@echo "HOST = $(HOST)"

# arch-tag: cfcae754-60d5-470f-b3ea-248fbf0a01c8
