#!/bin/sh
# Usage: update-version.sh DEFAULT_VERSION VERSION_SOURCE_FILE
#
# Update the C source file VERSION_SOURCE_FILE to define a ValTable
# containing various information about how Snogray was built (see
# "build-info.h" for the interface).
#
# VERSION_SOURCE_FILE will only be modifed if the contents have changed.
#
# If the following environment variables are set, they will be used to
# generate more information:
#
#   CC		   C compiler executable
#   CXX            C++ compiler executable
#   CC_OPTS	   Options used when compiling C programs
#   CXX_OPTS	   Options used when compiling C++ programs
#   CONFIG_STATUS  Autoconf "config.status" program
#

default_version="$1"
version_source_file="$2"

new_source="$version_source_file.new"

(
  echo '// this file is automatically generated by update-version.sh'
  echo '#include "build-info.h"'

  GIT_VERS=`git describe --dirty 2>/dev/null`

  VERSION=`echo ${GIT_VERS:-"$default_version"} | sed 's@^v@@'`

  # Extra interesting info; if these fail, fine, they'll just be ignored
  CONFIG=`$CONFIG_STATUS --config 2>/dev/null`
  CXX_VERS=`$CXX --version 2>/dev/null | sed 1q`
  CC_VERS=`$CC --version 2>/dev/null | sed 1q`
  if test x"$GIT_VERS" != x; then
    GIT_TAG=`echo "$GIT_VERS" | sed 's@-dirty$@@'`
    GIT_REV=`git rev-parse "$GIT_TAG"`
    GIT_REV_SUM=`git log -1 --pretty=tformat:%s "$GIT_TAG"`
    GIT_REV_DATE=`git log -1 --date=iso --pretty=tformat:%ad "$GIT_TAG"`
  fi

  cat <<EOF

static snogray::ValTable gen_info ()
{
  snogray::ValTable t;
EOF

  emit_table_set () {
    varname="$1"
    entryname="$2"
    eval isset='${'"$varname"':+set}'
    if test x"$isset" = xset; then
      eval val='$'"$varname"
      echo "  t.set (\"$entryname\", \"$val\");"
    fi
  }

  emit_table_set VERSION      "version"
  emit_table_set CONFIG	      "config"
  emit_table_set CXX	      "c++-compiler"
  emit_table_set CXX_OPTS     "c++-compiler-options"
  emit_table_set CXX_VERS     "c++-compiler-version"
  emit_table_set CC	      "c-compiler"
  emit_table_set CC_OPTS      "c-compiler-options"
  emit_table_set CC_VERS      "c-compiler-version"
  emit_table_set GIT_TAG      "git-tag"
  emit_table_set GIT_REV      "git-rev"
  emit_table_set GIT_REV_SUM  "git-rev-summary"
  emit_table_set GIT_REV_DATE "git-rev-date"

cat <<EOF
  return t;
}

const snogray::ValTable snogray::build_info (gen_info ());
EOF
) > "$new_source"

if cmp -s "$new_source" "$version_source_file"; then
  rm "$new_source"
else
  mv "$new_source" "$version_source_file"
fi
